config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login',
                                             sign_out: 'logout',
                                             edit: '/users/do/edit' }

  resources :chatrooms do
    member do
      put :favorite
    end
    resources :broadcasts do
      member do
        get :like, to: 'broadcasts#like'
        get :unlike, to: 'broadcasts#unlike'
      end
      resources :comments do
        member do
          get :like, to: 'comments#like'
          get :unlike, to: 'comments#unlike'
        end
      end
    end
  end

  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end

  resources :users, only: [:show, :profile, :index]

  resources :games do
    member do
      put :favorite
    end
  end

  resources :searching, path: '/search' do
    collection do
      get :autocomplete
    end
  end

  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  get '/users/do/profile', to: 'users#profile', as: 'profile'
  get '/tags/:tag', to: 'chatrooms#home', as: :tag

  root 'chatrooms#home'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :broadcast
  acts_as_votable

  validates :body, length: { minimum: 1, maximum: 500 }, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:like, :unlike, :show, :edit, :update, :destroy]

  def create
    @room = Chatroom.find(params[:chatroom_id])
    @broadcast = Broadcast.find(params[:broadcast_id])
    @comment = @broadcast.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @broadcast }
        format.js {}
      else
        format.html { redirect_to chatroom_path(@room), notice: 'Please try again.' }
      end
    end

  end


  def like
    @comment.liked_by current_user
    respond_to do |format|
      format.html { redirect_to chatroom_path(@comment.broadcast.chatroom) }
      format.js { render :layout => false }
    end
  end

  def unlike
    @comment.unliked_by current_user
    respond_to do |format|
      format.html { redirect_to chatroom_path(@comment.broadcast.chatroom) }
      format.js { render :layout => false }
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:broadcast_id, :body, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comm_with_reply">
    <div class="user_comment">
      <div class="user_comment_wrap">
        <%= image_tag comment.user.avatar(:thumb) %>
        <%= link_to user_path(comment.user.username) do %>
        <span class="comment_header"><%= comment.user.username.capitalize %></span>
        <% end %>

        <p class="comment_header_p"><span class="small_dot">·</span><%= distance_of_time_in_words(Time.now, comment.created_at) %> ago</p><br/>
        <p class="user_comment_text"><%= comment.body %><p class="comment_functions_p">
      </div>
        <div class="post_functions_area comment_footer">
            <% if current_user.liked? comment %>
                <%= link_to unlike_chatroom_broadcast_comment_path(comment.broadcast.chatroom, comment.broadcast, comment), class: 'thumb_btn rmv_btn unlike_broadcast', method: :get, remote: true do %>
                    <span class="rmv_thumb">Thumbed up</span><p class="v_count"><%= comment.get_likes.size %></p>
                <% end %>
            <% else %>
                <%= link_to like_chatroom_broadcast_comment_path(comment.broadcast.chatroom, comment.broadcast, comment), class: "thumb_btn like_broadcast", method: :get, remote: true do %>
                    <span>Thumbs up</span><p class="v_count"><%= comment.get_likes.size %></p>
                <% end %>
            <% end %>
        </div>
    </div>
        <!-- END -->
        <!-- REPLY COMMENT INPUT SECTION -->
        <!-- 
        <div class="reply_comm_section">
            <div class="user_comment_input" id="comm_reply_input">
                <%= image_tag current_user.avatar(:thumb) %>
                <textarea placeholder="Write a comment ..." name="message" class="input_field_comment"></textarea>
                <input type="submit" value="Post Comment" class="input_comment_btn">
            </div>
        </div>
        -->
        <!-- END COMMENT INPUT -->

    </div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :broadcast_id %><br>
    <%= f.number_field :broadcast_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_like.html.erb
<% if current_user.liked? comment %>
    <%= link_to unlike_chatroom_broadcast_comment_path(comment.broadcast.chatroom, comment.broadcast, comment), class: 'thumb_btn rmv_btn unlike_broadcast', method: :get, remote: true do %>
        <span class="rmv_thumb">Thumbed up</span><p class="v_count"><%= comment.get_likes.size %></p>
    <% end %>
<% else %>
    <%= link_to like_chatroom_broadcast_comment_path(comment.broadcast.chatroom, comment.broadcast, comment), class: "thumb_btn like_broadcast", method: :get, remote: true do %>
        <span>Thumbs up</span><p class="v_count"><%= comment.get_likes.size %></p>
    <% end %>
<% end %>

app/views/comments/create.js.erb
$('#comment_focused').val('');
$('#comment_focused').closest('.broadcastwindow').find('.post_comment_area').prepend('<%= j render @comment %>');
$('#comment_focused').closest('.broadcastwindow').find('.post_comment_area .comm_with_reply:first-child').attr('id', 'new_create');
$('html, body').animate({
  scrollTop: $("#new_create").offset().top
}, 900);

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Broadcast</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.broadcast_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/like.js.erb
$('.clicked_b').hide();
$('.clicked_b').closest('.comment_footer').append('<%= j render(:partial => "comments/like", locals: {comment: @comment}) %>');
$('.clicked_b').remove();

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Broadcast:</strong>
  <%= @comment.broadcast_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/unlike.js.erb
$('.clicked_b').hide();
$('.clicked_b').closest('.comment_footer').append('<%= j render(:partial => "comments/like", locals: {comment: @comment}) %>');
$('.clicked_b').remove();