config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login',
                                             sign_out: 'logout',
                                             edit: '/users/do/edit' }

  resources :chatrooms do
    member do
      put :favorite
    end
    resources :broadcasts do
      member do
        get :like, to: 'broadcasts#like'
        get :unlike, to: 'broadcasts#unlike'
      end
      resources :comments do
        member do
          get :like, to: 'comments#like'
          get :unlike, to: 'comments#unlike'
        end
      end
    end
  end

  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end

  resources :users, only: [:show, :profile, :index]

  resources :games do
    member do
      put :favorite
    end
  end

  resources :searching, path: '/search' do
    collection do
      get :autocomplete
    end
  end

  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  get '/users/do/profile', to: 'users#profile', as: 'profile'
  get '/tags/:tag', to: 'chatrooms#home', as: :tag

  root 'chatrooms#home'
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.mailbox.conversations
  end

  def inbox
    @conversations = current_user.mailbox.inbox
    render action: :index
  end

  def sent
    @conversations = current_user.mailbox.sentbox
    render action: :index
  end

  def trash
    @conversations = current_user.mailbox.trash
    render action: :index
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @conversation.mark_as_read(current_user)
  end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    recipient = User.find(params[:user_id])
    receipt   = current_user.send_message(recipient, params[:body], params[:subject])
    redirect_to conversation_path(receipt.conversation)
  end
end

app/views/conversations/index.html.erb
<div class="container" id="container2">
  <div class="body_fill_area">
    <h2>All Conversations</h2>

    <div class="splitter_light"></div>

    Unread (<%= current_user.mailbox.inbox.unread(current_user).count %>) |
    All Conversations (<%= current_user.mailbox.conversations.count %>) |
    Sent (<%= current_user.mailbox.sentbox.count %>) |
    Trash (<%= current_user.mailbox.trash.count %>)

    <div class="splitter_light"></div>

    Total: <%= @conversations.count %>

    <% @conversations.each do |conversation| %>
      <div>
        <% if conversation.is_unread?(current_user) %>
          <strong><%= link_to "#{conversation.subject}", conversation_path(conversation) %></strong>
        <% else %>
          <%= link_to "#{conversation.subject}", conversation_path(conversation) %>
        <% end %>
      </div>
    <% end %>

    <%= link_to "New Conversations", new_conversation_path %>
  </div>
</div>

app/views/conversations/new.html.erb
<div class="container" id="container2">
  <div class="body_fill_area">
    <h1>New Conversation</h1>

    <%= form_tag conversations_path, method: :post do %>
      <div>
        <%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :username) %>
      </div>

      <div>
        <%= text_field_tag :subject, nil, placeholder: "Subject" %>
      </div>

      <div>
        <%= text_area_tag :body, nil, placeholder: "Leave a comment" %>
      </div>

      <%= submit_tag %>
    <% end %>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="container" id="container2">
  <div class="body_fill_area">
    <h1><%= @conversation.subject %></h1>

    <% @conversation.receipts_for(current_user).each do |receipt| %>
      <div>
        <div><%= receipt.message.sender.username %> commented:</div>
        <p><%= receipt.message.body %></p>
      </div>
    <% end %>

    <%= form_tag conversation_messages_path(@conversation), method: :post do %>
      <div>
        <%= text_area_tag :body %>
      </div>

      <%= submit_tag %>
    <% end %>
  </div>
</div>